version: '3.8'

services:
  postgres17:
    image: postgres:17
    container_name: postgres17-uuidv7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uuidv7_benchmark
    ports:
      - "5432:5432"
    volumes:
      - postgres17_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres18:
    image: postgres:18beta1
    container_name: postgres18-uuidv7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uuidv7_benchmark
    ports:
      - "5433:5432"
    volumes:
      - postgres18_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres17_data:
  postgres18_data: